// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kong.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Acl
    {
        /// <summary>
        /// Initializes a new instance of the Acl class.
        /// </summary>
        public Acl()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Acl class.
        /// </summary>
        /// <param name="group">The arbitrary group name to associate to the
        /// consumer.</param>
        /// <param name="id">Uid.</param>
        /// <param name="createdAt">Milisec based timestamp of the create
        /// action</param>
        public Acl(string group = default(string), string id = default(string), int? createdAt = default(int?), ConsumerPreview consumer = default(ConsumerPreview))
        {
            Group = group;
            Id = id;
            CreatedAt = createdAt;
            Consumer = consumer;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the arbitrary group name to associate to the consumer.
        /// </summary>
        [JsonProperty(PropertyName = "group")]
        public string Group { get; set; }

        /// <summary>
        /// Gets or sets uid.
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or sets milisec based timestamp of the create action
        /// </summary>
        [JsonProperty(PropertyName = "created_at")]
        public int? CreatedAt { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "consumer")]
        public ConsumerPreview Consumer { get; set; }

    }
}
