// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kong.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class AclList
    {
        /// <summary>
        /// Initializes a new instance of the AclList class.
        /// </summary>
        public AclList()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AclList class.
        /// </summary>
        /// <param name="data">List of Acls.</param>
        /// <param name="total">Number of Acls for a Consumer.</param>
        public AclList(IList<Acl> data = default(IList<Acl>), int? total = default(int?))
        {
            Data = data;
            Total = total;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets list of Acls.
        /// </summary>
        [JsonProperty(PropertyName = "data")]
        public IList<Acl> Data { get; set; }

        /// <summary>
        /// Gets or sets number of Acls for a Consumer.
        /// </summary>
        [JsonProperty(PropertyName = "total")]
        public int? Total { get; set; }

    }
}
