// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kong.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ConsumerList
    {
        /// <summary>
        /// Initializes a new instance of the ConsumerList class.
        /// </summary>
        public ConsumerList()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ConsumerList class.
        /// </summary>
        /// <param name="data">List of Consumers.</param>
        /// <param name="next">Url to fetch next part of the Consumer
        /// list.</param>
        public ConsumerList(IList<Consumer> data = default(IList<Consumer>), string next = default(string))
        {
            Data = data;
            Next = next;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets list of Consumers.
        /// </summary>
        [JsonProperty(PropertyName = "data")]
        public IList<Consumer> Data { get; set; }

        /// <summary>
        /// Gets or sets url to fetch next part of the Consumer list.
        /// </summary>
        [JsonProperty(PropertyName = "next")]
        public string Next { get; set; }

    }
}
