// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kong.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class CredentialList
    {
        /// <summary>
        /// Initializes a new instance of the CredentialList class.
        /// </summary>
        public CredentialList()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CredentialList class.
        /// </summary>
        /// <param name="data">List of Credentials.</param>
        /// <param name="total">Number of Credentials for a Consumer.</param>
        public CredentialList(IList<Credential> data = default(IList<Credential>), int? total = default(int?))
        {
            Data = data;
            Total = total;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets list of Credentials.
        /// </summary>
        [JsonProperty(PropertyName = "data")]
        public IList<Credential> Data { get; set; }

        /// <summary>
        /// Gets or sets number of Credentials for a Consumer.
        /// </summary>
        [JsonProperty(PropertyName = "total")]
        public int? Total { get; set; }

    }
}
